### ISSUE TITLE
Push attempt to expired subscription の回避方法が分からない

### ISSUE THREAD

**Issue by eagletmt** [isucon/isucon10-final#196]
```
load: webpush: 不正な Web Push メッセージの送信がありました (/push/wITadUl9c8Eezvr9s9EL-RGgm0XiqwR3h4BlIJAElDM): Push attempt to expired subscription
load: webpush: 不正な Web Push メッセージの送信がありました (/push/xU5R6FZFaoTHEOF-T9n30HV8J5LKdNLIBiuKHckOFQQ): Push attempt to expired subscription
load: webpush: 不正な Web Push メッセージの送信がありました (/push/UxK-t8RKbYbDJVFNgKyQC0vEjSkCqV9fi9r3vf1W01Y): Push attempt to expired subscription
load: webpush: 不正な Web Push メッセージの送信がありました (/push/Hur7frGudAdmdgyljkB5qKuKuU4ogp4YzeqvWy4415E): Push attempt to expired subscription
Count:
  admin-answer-clarification: 139
  post-clarification: 140
  finish-benchmark: 875
  admin-get-clarification: 140
  list-notifications: 4231
  push-notifications: 3214
  get-clarification: 140
  join-member: 20
  get-dashboard: 500
  audience-get-dashboard: 21774
  admin-get-clarifications: 135
  enqueue-benchmark: 885
  resolve-clarification: 140
  create-team: 10
(11150 * 1.0) + 2177 - 400(err: 4, timeout: 215)
Pass: true / score: 12927 (13327 - 400)
```

みたいな結果になることがあって Push attempt to expired subscription で減点されてるっぽいんですが、これってどうやったら回避できるんでしょうか?
送ってみて 404 だったら push_subscriptions を削除するのは実装してあるはず #160 なんですが、ログ見る限り何度か送って 201 で成功した後の初めての 404 で減点されてそうに見えます。
